### ISSUE TITLE
backspace.fm みんなでワイワイ新年会 2015 企画書

### ISSUE THREAD

**Issue by drikin** [drikin/backspace#68]
# ToDo
- [x] 参加者への場所告知
- [x] プレゼント用意
- [x] backspace.fmステッカー
# 概要
- 日程: Saturday, January 17, 2015 at 7:00 PM ~ 9:30PM (二時間半）
- 会場: [跳魚](http://r.gnavi.co.jp/g840422/menu6/)予約名は「カイ」です
# 必要なモノ
- [x] HDR-MV1 + ミニ三脚 (drikin)
- [ ] HDR-MV1 + ミニ三脚 (mazzo)
- [ ] HDR-MV1 + ミニ三脚 (kai3)
- [ ] Belkinオーディオたこ足+ミニプラグケーブルx3 (mazzo)
- [x] Surface Pro 3 (drikin)
- [ ] モバイルホットスポット(au LTEテザリング) (kai3)
- [x] ポータブルプロジェクタ (drikin)
- [x] プレゼント (各自)
- [ ] タイムキーパー用iPad＋スタンド (kai3)
- [ ] 長めのACタップ (kai3 or mazzo)
- [ ] Webカメラ (kai3)
# タイムテーブル
- 19:00: 開場
- 19:15: 挨拶(mazzo)
- 19:30: 公開収録開始 
- 20:00: 席替え
- 19:50: 収録終了
- 21:00: プレゼントジャンケン大会 (kai3)
- 21:30: 締め &一次会解散
# 参加者
- [こちらを参照のこと](https://files.slack.com/files-pri/T02ABRDF3-F03ABCBEJ/__________________.md)
# 景品
- <a href="https://www.flickr.com/photos/drikin/16055107979" title="IMG_20150109_145321 by Kohichi Aoki, on Flickr"><img src="https://farm8.staticflickr.com/7575/16055107979_bba8d2c46b_t.jpg" width="75" height="100" alt="IMG_20150109_145321"></a>
  ロジテックソーラーキーボード
- <a href="https://www.flickr.com/photos/drikin/16055385197" title="IMG_20150109_145330 by Kohichi Aoki, on Flickr"><img src="https://farm8.staticflickr.com/7545/16055385197_a0d3bf600a_t.jpg" width="75" height="100" alt="IMG_20150109_145330"></a>
  ロジテックマルチキーボード
- <a href="https://www.flickr.com/photos/drikin/16215343516" title="IMG_20150109_145348 by Kohichi Aoki, on Flickr"><img src="https://farm9.staticflickr.com/8629/16215343516_3cb184b4e4_t.jpg" width="75" height="100" alt="IMG_20150109_145348"></a>
  7色に光るGoogleハブ
- <a href="https://www.flickr.com/photos/drikin/15621371413" title="IMG_20150109_145418 by Kohichi Aoki, on Flickr"><img src="https://farm8.staticflickr.com/7569/15621371413_a669bb1ec8_t.jpg" width="75" height="100" alt="IMG_20150109_145418"></a>
  Apple純正キーボード&トラックパッドアタッチメント
- <a href="https://www.flickr.com/photos/drikin/16215357136" title="IMG_20150109_145627 by Kohichi Aoki, on Flickr"><img src="https://farm9.staticflickr.com/8561/16215357136_f598e1a0fe_t.jpg" width="75" height="100" alt="IMG_20150109_145627"></a>
  ジュラルミンバンパー
- <a href="https://www.flickr.com/photos/drikin/16053796518" title="IMG_20150109_150615 by Kohichi Aoki, on Flickr"><img src="https://farm8.staticflickr.com/7548/16053796518_68b2b893f9_t.jpg" width="75" height="100" alt="IMG_20150109_150615"></a>
  Chromecast

カイプレ
- [Olasonic テレビスピーカー「TW-D5TV](http://av.watch.impress.co.jp/docs/news/20130304_590041.html)
- [デイテルジャパンがFCコントローラ風USBバッテリ発売。ゲーム機やスマホを「1UP充電」 - Engadget Japanese](http://japanese.engadget.com/2015/01/08/fc-usb-1up/)
# 新年会生放送台本
# ごあいさつ

こんにちは、backspace.fm 第78回です。
backspace.fmは一週間分のテック系ニュースをお届けするPodcastです。

(mz)今週の一言

(dk)今週の一言

(kai)今週の一言
## 新年会について (mazzo)

今回のbackspace.fm #078は、backspace.fm初のリスナー参加イベント「backspace.fm新年会2015」の開場からお届けします。

今回は1時間の時間厳守の収録なので、通常の構成と少し内容を変え、新年会に参加していただいている過去のゲストの皆様から1つずつ語りたいネタを提供していただき、そのネタについてみんなでワイワイ語っていきたいなと思います。
## 番組フィードバックについて (drikin)

生放送中にリアルタイムでフィードバックをする時は、http://backspace.fm/live.html のページ右下にある"Ask drikin now"のタブから、匿名でdrikin宛だけに直接メッセージを送ることも出来ます。

もちろんTwitter上で #backspacefm によるツイートは常に大歓迎です！
## 生放送スケジュールについて (kai3)

生放送スケジュールはGoogleカレンダーにて日程を公開しています。生放送を聞きたい方はぜひカレンダーを登録してください。
# 今週のスペシャル（50分）

今回はスペシャル編と言うことで新宴会に参加していただく過去ゲストの皆様に一ネタずつ持ち寄ってもらって、一人5分ずつくらいのライトニングトークをしていただけると嬉しいなと思っています。

時間の関係上時間厳守で進行する必要がありますが、ご了承ください。

現状順不同
1. シモケンさんネタ
   
   最近気になるガジェットネタ
2. まゆみんネタ
   
   Surface Pro3
3. 矢作さんネタ
   - [【イベントレポート】CES UnveiledでIoT機器が続々と登場 ～貼る体温計、貼る心拍計など、いずれもスマートフォン連携 - PC Watch](http://pc.watch.impress.co.jp/docs/news/event/20150105_682466.html)
4. 中澤さんネタ
   - [様々な人と出会い、地域を深く知る米国発の口コミサイト「Yelp」 | マイナビニュース](http://news.mynavi.jp/articles/2015/01/10/yelp/)
5. Otsuneさんネタ
   
   Ingressネタ
6. ジェットさんネタ
   
   2015年の注目ガジェット
7. KNN神田さんネタ
   
   Apple Watchについて
8. ゆずちゃんネタ
   
   最近一押しお笑い芸人ネタ
9. 増井さんネタ
   
   いま絶賛進行中のプロジェクトネタ（差し支えが無ければ）
10. shi3zさんネタ
    
    今年のAppleはどうなる?
11. 美波さん
    
    発明してほしい技術か、カヤックさん(昼間に創業メンバーと話す予定)について語ります！
# 次週予告・告知

(mz) 今週のbackspace.fmはいかがだったでしょうか？
この番組が気に入ったら、Podcastアプリで購読、Googleカレンダーで生放送予定をチェックしてみてください。  
購読先のリンクや、過去アーカイブなどの情報はURL backspace.fm から参照頂けます。  
ぜひ購読してください！

番組内容に関するフィードバックやリクエストなども #(ハッシュタグ)backspacefm にてツイートをお待ちしてます。

(dk) iTunesのレビューも大変参考になるので、気に入ったらレビューしていただけるとうれしいです！

来週からはまた通常配信に戻る予定です。今年もゲスト満載でお届けする予定なのでお楽しみに！

(all) ぜひ次回もお楽しみに！

**Comment by mazzo-p** [comment]
松尾プレ
iPhoneを充電できるスタイラスボールペン、使ってみた
https://medium.com/backstage-of-backspace/iphone-c4a3f9c740a7
寝ながら使える快適イヤフォン
http://www.amazon.co.jp/%E3%82%B5%E3%83%B3%E3%82%B3%E3%83%BC-SILICN53-%E3%82%B5%E3%83%B3%E3%82%B3%E3%83%BC%E5%AF%9D%E3%81%AA%E3%81%8C%E3%82%89%E4%BD%BF%E3%81%88%E3%82%8B%E5%BF%AB%E9%81%A9%E3%82%A4%E3%83%A4%E3%83%95%E3%82%A9%E3%83%B3/dp/B00RDR3H76/
